language: node_js
node_js:
- '8'
before_script:
  - git clone -b v2 git@github.ibm.com:bluemix-mobile-services/bmd-devops-pipeline.git
script: npm run lint && npm test && ./bmd-devops-pipeline/scripts/npm_publish.sh
notifications:
  slack: 
    rooms:
      - ibm-cloudplatform:${SLACK_ARF_DEVOPS_TOKEN}#arf-devops-codegen