language: node_js
node_js:
- '8'
before_script:
  - git clone -b v2 git@github.ibm.com:bluemix-mobile-services/bmd-devops-pipeline.git
script: npm run lint && npm test && ./bmd-devops-pipeline/scripts/npm_publish.sh
notifications:
  webhooks: https://hooks.slack.com/services/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